name: Deploy Pipeline
on:
  pull_request:
    branches: [ "dev" ]
    types:
      - closed

jobs:
  Digivance_Data:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/publish
    with:
      project_name: Digivance.Data
    secrets:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}

  Digivance_Data_EntityFramework:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/publish
    with:
      project_name: Digivance.Data.EntityFramework
    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
