name: PR Pipeline
on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get Digivance.Data version
      run: |
        project_version="$(grep '<Version>' < ./Digivance.Data/Digivance.Data.csproj | sed 's/.*<Version>\(.*\)<\/Version>/\1/')" |
        package_version="$($project_version)-pre.${{ github.run_number }}" |
        echo "Project Version: $project_version" |
        echo "Package Version: $package_version" |
        echo "DATA_VERSION=$package_version" >> $GITHUB_ENV
    
    - name: Display package version
      run: |
        echo ${{ env.DATA_VERSION }}
