name: PR Pipeline
on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get version
      id: package_version
      uses: KageKirin/get-csproj-version@v0
      with:
        file: Digivance.Data/Digivance.Data.csproj

    - name: Create tag
      run: |
        git tag -m "CI: create new tag" v${{ steps.test.package_version.version }}