name: PR Pipeline
on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get Digivance.Data version
      run: |
        version=$(grep '<Version>' < ./Digivance.Data/Digivance.Data.csproj | sed 's/.*<Version>\(.*\)<\/Version>/\1/')
        package_version=$(echo "$($version)-pre.${{ github.run_number }}")
        echo $package_version
        echo "DATA_VERSION=$package_version" >> $GITHUB_ENV
    
    - name: Set pre release version
      env:
        DATA_VERSION: ${{ env.DATA_VERSION }}
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        echo "DATA_VERSION=$($DATA_VERSION})-pre.$($RUN_NUMBER)" >> $GITHUB_ENV

    - name: Display package version
      run: |
        echo ${{ env.DATA_VERSION }}
